site_name: Stormtrooper
site_description: 'Zero and few-shot classification with transformer models.'
repo_url: https://github.com/centre-for-humanities-computing/stormtrooper

nav:
  - Getting Started: index.md
  - Models: models.md

theme:
  name: material
  logo: "https://raw.githubusercontent.com/centre-for-humanities-computing/stormtrooper/main/assets/logo.svg"
  navigation_depth: 4
  palette:
    primary: white
  features:
      - toc.integrate
      - navigation.path
      - navigation.indexes
      - toc.follow
      - content.code.copy

plugins:
- mkdocstrings:
    handlers:
      python:
        options:
          annotations_path: brief
          show_root_heading: true
          show_root_toc_entry: false
          show_symbol_type_heading: true
          docstring_style: numpy
          heading_level: 3

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - admonition
  - toc:
      toc_depth: 2
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
