# creates the documentation on pushes it to the gh-pages branch
name: Documentation

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]


permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "stormtrooper" "griffe==0.4.0" "mkdocstrings==0.22.0" "mkdocs==1.5.3" "mkdocs-material==9.5.6" "mkdocstrings-python==1.8.0"

      - name: Build and Deploy
        if: github.event_name == 'push'
        run: mkdocs gh-deploy --force
      
      - name: Build
        if: github.event_name == 'pull_request'
        run: mkdocs build
